package main;

import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.events.SelectionListener;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Tree;
import org.eclipse.swt.widgets.TreeItem;

public class ObjectListTab extends Composite {
	private Document attachedDocument;

	/////////////////////////////////
	// Begin autogenerated code

	private Button buttonUp;
	private Button buttonDown;
	private Button delete;
	private Tree tree;

	/////////////////////////////////
	// End autogenerated code

	/**
	 * Create the composite.
	 * 
	 * @param parent
	 * @param style
	 */
	/////////////////////////////////
	// Begin autogenerated code
	public ObjectListTab(Composite parent, int style) {
		super(parent, style);
		setLayout(new GridLayout(1, false));

		tree = new Tree(this, SWT.BORDER);
		tree.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true, 1, 1));

		Composite composite = new Composite(this, SWT.NONE);
		composite.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, false, false, 1, 1));
		composite.setLayout(new FillLayout(SWT.HORIZONTAL));

		buttonUp = new Button(composite, SWT.NONE);
		buttonUp.setText("Up");

		buttonDown = new Button(composite, SWT.NONE);
		buttonDown.setText("Down");

		delete = new Button(composite, SWT.NONE);
		delete.setText("Delete");

		/////////////////////////////////
		// End autogenerated code

		tree.addSelectionListener(SelectionListener.widgetSelectedAdapter(this::forwardSelectionEvent));

		attachedDocument = DocumentManager.getCurrentDocument();
		var selectionListener = attachedDocument.addSelectionListener(this::rectSelected);
		var changeListener = attachedDocument.getUndoStack().addListener(action->populate());
		var listener = DocumentManager.addSelectionListener(document-> {
			attachedDocument.removeSelectionListener(selectionListener);
			attachedDocument.getUndoStack().removeListener(changeListener);
			attachedDocument = document;
			document.addSelectionListener(selectionListener);
			document.getUndoStack().addListener(changeListener);
			populate();
		});

		buttonUp.addSelectionListener(SelectionListener.widgetSelectedAdapter(this::onButtonUp));
		buttonDown.addSelectionListener(SelectionListener.widgetSelectedAdapter(this::onButtonDown));
		delete.addSelectionListener(SelectionListener.widgetSelectedAdapter(this::onDelete));

		buttonUp.setEnabled(false);
		buttonDown.setEnabled(false);
		delete.setEnabled(false);

		// Clean up listeners.
		addDisposeListener(event-> {
			DocumentManager.removeSelectionListener(listener);
			attachedDocument.removeSelectionListener(selectionListener);
			attachedDocument.getUndoStack().removeListener(changeListener);
		});
	}

	private void onButtonUp(SelectionEvent e) {
		var document = DocumentManager.getCurrentDocument();
		var index = document.getSelectedIndex();
		assert (index != -1);
		if (index > 0) {
			document.setPosition(document.getSelectedRectangle(), index - 1);
		}
	}

	private void onButtonDown(SelectionEvent e) {
		var document = DocumentManager.getCurrentDocument();
		var index = document.getSelectedIndex();
		assert (index != -1);
		if (index < document.getRectangles().size() - 1) {
			document.setPosition(document.getSelectedRectangle(), index + 1);
		}
	}

	private void onDelete(SelectionEvent e) {
		var document = DocumentManager.getCurrentDocument();
		var rect = document.getSelectedRectangle();
		assert (rect != null);
		var index = document.getSelectedIndex();
		document.removeRectangle(rect);

		// Select a new rectangle.
		index = Math.min(index, document.getRectangles().size() - 1);
		document.setSelectedRectangle(index);
	}

	private void forwardSelectionEvent(SelectionEvent e) {
		if (e.widget == null) {
			DocumentManager.getCurrentDocument().setSelectedRectangle(null);
		} else {
			int index = tree.indexOf((TreeItem) e.item);
			DocumentManager.getCurrentDocument().setSelectedRectangle(index);
		}
	}

	private void rectSelected(Rectangle rect) {
		if (rect == null) {
			tree.deselectAll();
			buttonUp.setEnabled(false);
			buttonDown.setEnabled(false);
			delete.setEnabled(false);
		} else {
			var index = attachedDocument.getSelectedIndex();
			tree.select(tree.getItem(index));
			buttonUp.setEnabled(index > 0);
			buttonDown.setEnabled(index < attachedDocument.getRectangles().size() - 1);
			delete.setEnabled(true);
		}
	}

	/**
	 * Call this when the data array changes.
	 */
	public void populate() {
		var file = DocumentManager.getCurrentDocument();
		var data = file.getRectangles();
		String[] entries = new String[data.size()];
		for (int i = 0; i < entries.length; i++) {
			entries[i] = data.get(i).toString();
		}

		tree.removeAll();
		tree.deselectAll();
		for (var entry : entries) {
			var item = new TreeItem(tree, SWT.NONE);
			item.setText(entry);
		}

		// Fake a selection event.
		rectSelected(file.getSelectedRectangle());
	}

	@Override
	protected void checkSubclass() {
		// Disable the check that prevents subclassing of SWT components
	}
}
